from startouchclass import SingleArm
import time

# 创建机械臂连接  连接接口为"can0"
arm_controller = SingleArm(can_interface_ = "can0")
time.sleep(2)
# print(f"distance_now:{arm_controller.get_gripper_distance()},pos:{arm_controller.get_gripper_position()}")
# print("target pos raw : 1")
# arm_controller.setGripperPosition_raw(1)
# time.sleep(2)
# print(f"distance_now:{arm_controller.get_gripper_distance()},pos:{arm_controller.get_gripper_position()}")
# print("target pos raw : 0")
# arm_controller.setGripperPosition_raw(0)
# time.sleep(2)
# print(f"distance_now:{arm_controller.get_gripper_distance()},pos:{arm_controller.get_gripper_position()}")
# print("target pos raw : 0.5")
# arm_controller.setGripperPosition_raw(0.5)
# time.sleep(2)
# print(f"distance_now:{arm_controller.get_gripper_distance()},pos:{arm_controller.get_gripper_position()}")
# print("target pos : 1")
# arm_controller.setGripperPosition(1)
# time.sleep(2)
# print(f"distance_now:{arm_controller.get_gripper_distance()},pos:{arm_controller.get_gripper_position()}")
# print("target pos : 0.5")
# arm_controller.setGripperPosition(0.5)
# time.sleep(2)
print(f"distance_now:{arm_controller.get_gripper_distance()},pos:{arm_controller.get_gripper_position()}")
print("target dis : 0.085")
arm_controller.setGripperDistance(0.085)
time.sleep(2)
print(f"distance_now:{arm_controller.get_gripper_distance()},pos:{arm_controller.get_gripper_position()}")
print("target dis : 0.0425")
arm_controller.setGripperDistance(0.0425,15)
time.sleep(2)
arm_controller.setGripperDistance(0.0,15,0.1)
time.sleep(2)
print(f"distance_now:{arm_controller.get_gripper_distance()},pos:{arm_controller.get_gripper_position()}")
print("target dis : 0")
arm_controller.setGripperDistance(0.085)
print(arm_controller.get_ee_pose_euler())
print(arm_controller.get_ee_pose_quat())
time.sleep(2)
# print(arm_controller.get_ee_pose_euler())
# print(arm_controller.get_ee_pose_quat())
#time.sleep(2)
arm_controller.cleanup()
