kinematics:
  tool:
    xyz: [0.15584, 0.0, 0.0]
    rpy: [0.0, 0.0, 0.0]
  payload:
    mass: 0.126
    com: [0.072, 0, 0.082] #相对于Joint6的Origin的质心    # inertia is optional and not required for current payload handling

motor_signs: [1, 1, -1, -1, -1, 1]

pos_vel_mode:
  max_acc_limits: [28.0, 28.0, 28.0, 22.0, 26.0, 26.0]
  max_dec_limits: [-28.0, -28.0, -28.0, -22.0, -26.0, -26.0]
  kp_apr_limits: [250.0, 250.0, 260.0, 100.0, 100.0, 100.0]

mit_mode:
  kp: [300.0, 490.0, 490.0, 65.0,  45.0,  45.0]
  kd: [ 16.0, 15,  12.5,   2,   2,  2] 
  gravity_tau_limits: [27.0, 27.0, 27.0, 7.0, 12.5, 12.5]
  gravity_comp_scale: 1.05
